name: Continuous Integration
on:
    push:
        branches:
            - main
jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js v16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint

    Testing:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "14"
            - name: Install dependencies
              run: npm ci
            - name: Test
              run: npm run test:coverage
            - name: Store code coverage report
              uses: actions/upload-artifact@v2
              with:
                name: coverage
                path: coverage/

    Upload_Coverage_Report:
        name: Upload coverage report to codecov
        needs: [Testing]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
              with:
                fetch-depth: 2
            - name: Download Coverage report
              uses: actions/download-artifact@v2
              with:
                name: coverage
                path: coverage/
            - name: Codecov Upload
              uses: codecov/codecov-action@v1
                with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: coverage/
                  fail_ci_if_error: true
