name: Continuous Delivery
on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Setup Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn release

    docs:
        name: Build and Deploy API Docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
            - name: Use Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: 16
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install
            - name: Build Docs
              run: yarn docs
            - name: Deploy Docs
              uses: JamesIves/github-pages-deploy-action@0f24da7de3e7e135102609a4c9633b025be8411b # renovate: tag=4.1.5
              with:
                branch: gh-pages # The branch the action should deploy to.
                folder: docs # The folder the action should deploy.
