name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4 # renovate: tag=v4
            - name: Use Node.js v16
              uses: actions/setup-node@v4 # renovate: tag=v4
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@v4 # renovate: tag=v4
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Run ESLint
              run: yarn lint

    Build:
        name: Build Source Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4 # renovate: tag=v4
            - name: Use Node.js v16
              uses: actions/setup-node@v4 # renovate: tag=v4
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@v4 # renovate: tag=v4
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Build
              run: yarn build

    Testing:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 # renovate: tag=v4
            - name: Use Node.js v16
              uses: actions/setup-node@v4 # renovate: tag=v4
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@v4 # renovate: tag=v4
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Test
              run: yarn test:coverage
            - name: Store code coverage report
              uses: actions/upload-artifact@v4 # renovate: tag=v4
              with:
                  name: coverage
                  path: coverage/

    Upload_Coverage_Report:
        name: Upload coverage report to codecov
        needs: [Testing]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4 # renovate: tag=v4
              with:
                  fetch-depth: 2
            - name: Download Coverage report
              uses: actions/download-artifact@v4 # renovate: tag=v4
              with:
                  name: coverage
                  path: coverage/
            - name: Codecov Upload
              uses: codecov/codecov-action@v4 # renovate: tag=v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: coverage/
                  fail_ci_if_error: true
