name: Continuous Integration
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
            - name: Use Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: 16
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install
            - name: Run ESLint
              run: yarn lint

    Build:
        name: Build Source Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
            - name: Use Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: 16
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install
            - name: Run tsc
              run: yarn build

    Testing:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
            - name: Setup Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: "16"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install
            - name: Test
              run: npm run test:coverage
            - name: Store code coverage report
              uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
              with:
                  name: coverage
                  path: coverage/

    Upload_Coverage_Report:
        name: Upload coverage report to codecov
        needs: [Testing]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
              with:
                  fetch-depth: 2
            - name: Download Coverage report
              uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2
              with:
                  name: coverage
                  path: coverage/
            - name: Codecov Upload
              uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # renovate: tag=v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  directory: coverage/
                  fail_ci_if_error: true

    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - name: Setup Node.js
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: "16"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn release
